name: Prettier Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]

    name: Running on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.5"

      - name: Setup Prettier
        run: npm i -g prettier

      - name: Check Prettier
        run: prettier --check .
