name: Dprint Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]

    name: Running on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dprint
        shell: bash
        run: |
          curl -fsSL https://dprint.dev/install.sh | sh -s 0.17.0 > /dev/null 2>&1
          echo "/home/runner/.dprint/bin" >> $GITHUB_PATH

      - name: Check formatting
        shell: bash
        run: dprint check
          
