name: Dprint Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]

    name: Running on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: dprint/check@v2.0
